### ISSUE TITLE
Testing Version 2.1.0

### ISSUE THREAD

**Issue by Bars92** [Bars92/font-organizer#4]
## Regression Checklist:

- [x] General Settings options saving and working.
- [ ] Upload fonts:
   - [ ] Upload all supported formats.
   - [ ] Upload more than 1 file.
   - [ ] Upload non-normal font weight.
   - [ ] Upload to an existing font name.
- [x] Available fonts:
   - [x] List does not contain an used font.
   - [x] Adding an available font is added to used fonts.
   - [x] List is sorted.
- [x] Known Elements:
   - [x] Known element is saving and working properly.
   - [x] Known element are using the correct font weight.
   - [x] Known element working as expected with 'Not Stated' font weight.
- [x] Custom Elements:
   - [x] Custom elements is saving and working properly.
   - [x] Custom elements is using the font weight.
- [x] Manage fonts:
   - [x] Selecting a font displays all the correct information (urls, name, custom elements)
   - [x] Delete font (Google & custom) delete the font from the database (usable font) and the file.
   - [x] Editing custom elements in manage fonts is working as expected for all the fields.
- [x] Preview is displaying the font and text preview when selecting font and text.
- [x] All plugin links are working and redirecting to the desired address.
- [ ] Updating the plugin does update the necessary tables and working.
- [ ] Plugin readme.txt is set to the newest version and updated.

**Comment by YardenSadeHive** [comment]
I will open temporarily new staging enviorment because the hivewebstudios.com website cannot be "played" with at the time.
Will post login info on slack soon.

**Comment by YardenSadeHive** [comment]
[BUG] Going to advanced tab -> return to General tab -> add google font -> after "use this font" button is clicked the page is refreshed and shows the advanced tab. (Wanted behavior: The general tab will show instead since it was the last tab)
